services:

  runtime-setup:
    image: vscode-swift:22.04-6.0-insiders
    build:
      args:
        base_image: "swiftlang/swift:nightly-6.0-jammy"

  test:
    image: vscode-swift:22.04-6.0-insiders
    environment:
      - VSCODE_VERSION=insiders

  shell:
    image: vscode-swift:22.04-6.0-insiders
