//===----------------------------------------------------------------------===//
//
// This source file is part of the VSCode Swift open source project
//
// Copyright (c) 2022 the VSCode Swift project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of VSCode Swift project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import * as vscode from "vscode";
import * as langclient from "vscode-languageclient/node";
import { LanguageClientManager } from "./LanguageClientManager";

/**
 * Registers a {@link vscode.TextDocumentContentProvider TextDocumentContentProvider} that will display
 * the interface for a swiftmodule. The swiftmodule interface is generated by SourceKit-LSP
 */
export function getSwiftModuleDocumentProvider(
    languageClientManager: LanguageClientManager
): vscode.Disposable {
    const provider = vscode.workspace.registerTextDocumentContentProvider("swiftmodule", {
        provideTextDocumentContent: async uri => {
            try {
                return await languageClientManager.useLanguageClient(async (client, token) => {
                    const params = {
                        textDocument: client.code2ProtocolConverter.asUri(uri),
                    };
                    const response = await client.sendRequest(
                        swiftModuleDocumentRequest,
                        params,
                        token
                    );
                    return response.contents;
                });
            } catch (error) {
                return `swiftmodule ${uri.path} failed to load`;
            }
        },
    });
    return provider;
}

// Definitions for custom swiftmodule document generation requests used by sourcekit-lsp
interface SwiftModuleDocumentParams {
    /**
     * The text document.
     */
    textDocument: langclient.DocumentUri;
}

interface SwiftModuleDocument {
    /**
     * The swiftmodule interface contents
     */
    contents: string;
}

const swiftModuleDocumentRequest = new langclient.RequestType<
    SwiftModuleDocumentParams,
    SwiftModuleDocument,
    unknown
>("sourcekit-lsp/swiftModule");
