#!/bin/sh
VSCODE_SWIFT_ASKPASS_FILE=$(mktemp)

ELECTRON_RUN_AS_NODE="1" VSCODE_SWIFT_ASKPASS_FILE="$VSCODE_SWIFT_ASKPASS_FILE" "$VSCODE_SWIFT_ASKPASS_NODE" "$VSCODE_SWIFT_ASKPASS_MAIN"
EXIT_CODE=$?

cat "$VSCODE_SWIFT_ASKPASS_FILE"
rm "$VSCODE_SWIFT_ASKPASS_FILE"

exit "$EXIT_CODE"
