name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  package:
    name: Package Extension
    runs-on: ubuntu-latest
    container:
      image: swift:6.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Extension
        run: |
          export NODE_VERSION=v18.19.0
          export NODE_PATH=/usr/local/nvm/versions/node/v18.19.0/bin
          export NVM_DIR=/usr/local/nvm
          . .github/workflows/scripts/setup-linux.sh
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          npm ci
          npm run compile
          npm run package
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vscode-swift-extension
          path: |
            *.vsix
  tests_release:
    name: Test Release
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      # Linux
      linux_env_vars: |
        NODE_VERSION=v18.19.0
        NODE_PATH=/usr/local/nvm/versions/node/v18.19.0/bin
        NVM_DIR=/usr/local/nvm
        CI=1
      linux_pre_build_command: . .github/workflows/scripts/setup-linux.sh
      linux_build_command: ./scripts/test.sh
      # Windows
      windows_env_vars: |
        CI=1
        VSCODE_TEST=1
      windows_pre_build_command: .github\workflows\scripts\windows\install-nodejs.ps1
      windows_build_command: scripts\test_windows.ps1
      enable_windows_docker: false

  tests_insiders:
    name: Test Insiders
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      # Linux
      linux_exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "nightly-6.1"}, {"swift_version": "nightly-main"}]'
      linux_env_vars: |
        NODE_VERSION=v18.19.0
        NODE_PATH=/usr/local/nvm/versions/node/v18.19.0/bin
        NVM_DIR=/usr/local/nvm
        CI=1
        VSCODE_TEST=1
        VSCODE_VERSION=insiders
      linux_pre_build_command: . .github/workflows/scripts/setup-linux.sh
      linux_build_command: ./scripts/test.sh
      # Windows
      windows_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "nightly-6.0"}, {"swift_version": "nightly"}]'
      windows_env_vars: |
        CI=1
        VSCODE_TEST=1
        VSCODE_VERSION=insiders
      windows_pre_build_command: .github\workflows\scripts\windows\install-nodejs.ps1
      windows_build_command: scripts\test_windows.ps1
      enable_windows_docker: false
