name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests_release:
    name: Test Release
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      # Linux
      linux_env_vars: |
        NODE_VERSION=v18.19.0
        NODE_PATH=/usr/local/nvm/versions/node/v18.19.0/bin
        NVM_DIR=/usr/local/nvm
        CI=1
      linux_pre_build_command: |
        apt-get update && apt-get install -y rsync curl gpg libasound2 libgbm1 libgtk-3-0 libnss3 xvfb build-essential
        mkdir -p $NVM_DIR
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION"
        echo "$NODE_PATH" >> $GITHUB_PATH
      linux_build_command: ./docker/test.sh
      # Windows
      windows_env_vars: |
        CI=1
        VSCODE_TEST=1
      windows_pre_build_command: .github\workflows\scripts\windows\install-nodejs.ps1
      windows_build_command: docker\test-windows.ps1
      enable_windows_docker: false

  tests_insiders:
    name: Test Insiders
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      # Linux
      linux_exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "nightly-6.0"}, {"swift_version": "nightly-main"}]'
      linux_env_vars: |
        NODE_VERSION=v18.19.0
        NODE_PATH=/usr/local/nvm/versions/node/v18.19.0/bin
        NVM_DIR=/usr/local/nvm
        CI=1
        VSCODE_TEST=1
        VSCODE_VERSION=insiders
      linux_pre_build_command: . .github/workflows/scripts/setup-linux.sh
      linux_build_command: ./docker/test.sh
      # Windows
      windows_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "nightly-6.0"}, {"swift_version": "nightly"}]'
      windows_env_vars: |
        CI=1
        VSCODE_TEST=1
        VSCODE_VERSION=insiders
      windows_pre_build_command: .github\workflows\scripts\windows\install-nodejs.ps1
      windows_build_command: docker\test-windows.ps1
      enable_windows_docker: false
