name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: "0 0 * * *"

env:
  LINUX_ENV_VARS: |
    NODE_VERSION=v18.19.0
    NODE_PATH=/usr/local/nvm/versions/node/v18.19.0/bin
    NVM_DIR=/usr/local/nvm
    CI=1
    VSCODE_TEST=1
    FAST_TEST_RUN=${{ github.event_name == 'schedule' && '1' || '0' }}
  LINUX_PRE_BUILD_COMMAND: |
    apt-get update && apt-get install -y rsync curl gpg libasound2 libgbm1 libgtk-3-0 libnss3 xvfb build-essential
    mkdir -p $NVM_DIR
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION"
    echo "$NODE_PATH" >> $GITHUB_PATH
  WINDOWS_ENV_VARS: |
    CI=1
    VSCODE_TEST=1
    FAST_TEST_RUN=${{ github.event_name == 'schedule' && '1' || '0' }}
  WINDOWS_PRE_BUILD_COMMAND: |
    .github\workflows\scripts\windows\install-nodejs.ps1

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      # Linux
      linux_exclude_swift_versions: '[{"swift_version": "nightly-main"}]'
      linux_env_vars: $LINUX_ENV_VARS
      linux_pre_build_command: eval $LINUX_PRE_BUILD_COMMAND
      linux_build_command: ./docker/test.sh
      # Windows
      windows_exclude_swift_versions: '[{"swift_version": "nightly"}]'
      windows_env_vars: $WINDOWS_ENV_VARS
      windows_pre_build_command: $WINDOWS_PRE_BUILD_COMMAND
      windows_build_command: docker\test-windows.ps1
      enable_windows_docker: false

  tests_insiders:
    name: Test Insiders
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    # if: github.event.schedule
    with:
      # Linux
      linux_exclude_swift_versions: '[{"swift_version": "nightly-main"}]'
      linux_env_vars: |
        $LINUX_ENV_VARS
        VSCODE_VERSION='insiders'
      linux_pre_build_command: eval $LINUX_PRE_BUILD_COMMAND
      linux_build_command: ./docker/test.sh
      # Windows
      windows_exclude_swift_versions: '[{"swift_version": "nightly"}]'
      windows_env_vars: |
        $WINDOWS_ENV_VARS
        VSCODE_VERSION='insiders'
      windows_pre_build_command: $WINDOWS_PRE_BUILD_COMMAND
      windows_build_command: docker\test-windows.ps1
      enable_windows_docker: false

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      # Pending https://github.com/swiftlang/vscode-swift/pull/1176
      license_header_check_enabled: false
      license_header_check_project_name: "VS Code Swift"
      api_breakage_check_enabled: false
      docs_check_enabled: false
      format_check_enabled: false
      shell_check_enabled: true
      unacceptable_language_check_enabled: true
